list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/demo3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/demo3.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/mdi_icon_font16_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/mdi_icon_font18_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/mdi_icon_font24_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/roboto_regular_12_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/roboto_regular_16_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/home/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_heading_card/ha_heading_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_heading_card/ha_heading_card_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_heading_card/ha_heading_card.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_ripple/ha_ripple_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_ripple/ha_ripple_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/ha_ripple/ha_ripple.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_badge/hui_heading_badge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_badge/hui_heading_badge_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_badge/hui_heading_badge.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_card/hui_heading_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_card/hui_heading_card_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/hui_heading_card/hui_heading_card.c)